-- MySQL Workbench Synchronization
-- Generated: 2021-03-27 18:23
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: Sanches

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `Task10` DEFAULT CHARACTER SET utf8 ;

CREATE TABLE IF NOT EXISTS `Task10`.`product` (
  `maker` VARCHAR(10) NULL DEFAULT NULL,
  `model` VARCHAR(50) NOT NULL,
  `type` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`model`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `Task10`.`pc` (
  `code` INT(11) NOT NULL,
  `model` VARCHAR(50) NULL DEFAULT NULL,
  `speed` SMALLINT(6) NULL DEFAULT NULL,
  `ram` SMALLINT(6) NULL DEFAULT NULL,
  `hd` REAL NULL,
  `cd` VARCHAR(10) NULL DEFAULT NULL,
  `price` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`code`),
  INDEX `model_pc_idx` (`model` ASC) VISIBLE,
  CONSTRAINT `model_pc`
    FOREIGN KEY (`model`)
    REFERENCES `Task10`.`product` (`model`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `Task10`.`laptop` (
  `code` INT(11) NOT NULL,
  `model` VARCHAR(50) NULL DEFAULT NULL,
  `speed` SMALLINT(6) NULL DEFAULT NULL,
  `ram` SMALLINT(6) NULL DEFAULT NULL,
  `hd` REAL NULL,
  `price` DOUBLE NULL DEFAULT NULL,
  `screen` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`code`),
  INDEX `model_laptop_idx` (`model` ASC) VISIBLE,
  CONSTRAINT `model_laptop`
    FOREIGN KEY (`model`)
    REFERENCES `Task10`.`product` (`model`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `Task10`.`printer` (
  `code` INT(11) NOT NULL,
  `model` VARCHAR(50) NULL DEFAULT NULL,
  `color` CHAR(1) NULL DEFAULT NULL,
  `type` VARCHAR(10) NULL DEFAULT NULL,
  `price` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`code`),
  INDEX `model_printer_idx` (`model` ASC) VISIBLE,
  CONSTRAINT `model_printer`
    FOREIGN KEY (`model`)
    REFERENCES `Task10`.`product` (`model`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
